pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                cleanWs()
                dotnetRestore project: "FixLife.ClientApp.csproj"
                dotnetClean project: "FixLife.ClientApp.csproj"
            }
        }
        
        stage('Build') {
            steps {
                dotnetBuild configuration: 'Release', versionSuffix:"${env.BUILD_NUMBER}"
            }
        }
        
        stage('Publish') {
          steps {
            dotnetPublish configuration: 'Release', project: "FixLife.ClientApp.csproj"
          }
        }
        
        stage('Publish') {
          steps {
            archiveArtifacts artifacts: '**'
          }
        }
    }
}