name: FixLife.ClientApp
# TODO: Tests and add signing keys
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  DOTNETVERSION:  8.x

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v2
      - name: Setup .NET VERSION ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'

      - name: Install .NET MAUI
        shell: pwsh
        run: |
          dotnet workload restore
          dotnet nuget locals all --clear
          dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
          
      - name : Build and Run Tests
        run: |
          cd .\FixLife.ClientApp
          dotnet clean
          dotnet build
          dotnet test

      - name: Build Windows
        run: |
          cd FixLife.ClientApp
          dotnet publish -f net8.0-windows10.0.22621.0 -c Release

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-windows
          path: |
            **\*.msix
        
      
  buildAndroid:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v2
      - name: Setup .NET VERSION ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'

      - name: Extract Android signing key from env
        shell: bash
        run: |
              echo "${{ secrets.RELEASE_KEYSTORE }}" > FixLife.keystore.asc
              gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch FixLife.keystore.asc > FixLife.keystore
      
      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet workload restore
          dotnet nuget locals all --clear
          dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
      - name: Restore nuget
        run: |
          cd .\FixLife.ClientApp
          dotnet clean
          dotnet restore FixLife.ClientApp.csproj
      
      - name : Build and Run Tests
        run: |
          cd .\FixLife.ClientApp
          dotnet build FixLife.ClientApp.csproj -c Release -f net8.0-android /p:AndroidSigningKeyStore=FixLife.keystore /p:AndroidSigningKeyPass=ghactionskey /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}" --no-restore
          dotnet test
          
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-android
          path: |
            **\*.aab
            **\*.apk
