name: FixLife.WebApi-Docker-Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:
  
env:
  DOTNETVERSION:  8.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET VERSION ${{env.DOTNETVERSION}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{env.DOTNETVERSION}}'
    - name: Restore NuGet
      run: |
          cd ./FixApp.WebAPI
          dotnet nuget locals all --clear
          dotnet restore
    - name: Build and Test
      run: |
          cd ./FixApp.WebAPI
          dotnet workload restore
          dotnet clean
          dotnet build FixApp.WebAPI.csproj
          dotnet test FixApp.WebAPI.csproj
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd ./FixApp.WebAPI
        docker build . --file Dockerfile --tag FixLife.WebAPI:$(date +%s)
